### ISSUE TITLE
installed the windows version

### ISSUE THREAD

**Issue by samashley** [Mobirise/Mobirise#4]
I installed Mobirise under wine on ubuntu 14.4 "trusty" and got the following when the .wine folder was scanned with clamav. Please comment.

/home/myusername/.wine/drive_c/Program Files (x86)/Mobirise/Qt5Core.dll: Win.Trojan.Ramnit-6068 FOUND
/home/myusername/.wine/drive_c/Program Files (x86)/Mobirise/Qt5WebKit.dll: Win.Trojan.Ramnit-6196 FOUND

**Comment by Mobirise** [comment]
It's a known problem of ClamAV, check for example
http://forums.clamwin.com/viewtopic.php?t=4111 - it detects it in Photoshop and Opera:
"It seems like someone mentioned a Ramnit detection some time ago--maybe in the last 2/3 months, but I don't recall whether or not it was a false postive. To be save, you should regard any detection as a virus until you find out otherwise. If the file has been on your computer and you have used it recently without any trouble, and it has not been changed, it is likely a false postive. I wouldn't try to guess, however, so I recommend you scan it with Jotti or Virus Total online. If a couple of other AVs detect something besides the Clam AV engine we use, then it is likely a real infection. If Clam AV is the only AV detecting something, then it is likely a false positive."

Also check 100% clear virustotal reports for mobirise files: 
https://www.virustotal.com/en/file/1f4869ab563bdc51e3a0dd588b8b15b7df5efe895a6a326e43020dcbdd79c9bc/analysis/
https://www.virustotal.com/en/file/85f080179b7f652808867cd9c45b8f117bc94464465e5d18401bcdf1ef79439a/analysis/1452613268/

**Comment by adegard** [comment]
Hi, 
I like a lot Mobirise, but I add the same issue in Clam AV on Windows OS:

> C:\Program Files\Mobirise\Qt5Core.dll: Win.Trojan.Ramnit-5759 FOUND
> C:\Program Files\Mobirise\Qt5WebKit.dll: Win.Trojan.Ramnit-5881 FOUND

Could you provide an updated virus-clean report (2018) of Mobirise software? 
Thank you very much
